### ISSUE TITLE
Fix Poltergeist error: element overlap

### ISSUE THREAD

**Issue by wopian** [wopian/material-slackthemes#14]
/home/travis/build/wopian/material-slackthemes/vendor/bundle/ruby/2.1.0/gems/poltergeist-1.6.0/lib/capybara/poltergeist/node.rb:23:in `rescue in command': Firing a click at co-ordinates [256.5, 728.5] failed. Poltergeist detected another element with CSS selector 'html.supports_line_clamp.supports_flexbox.no_touch body.light_theme.index div.ng-scope div#client-ui.container-fluid.sidebar_theme_custom_theme div#fs_modal.fs_modal_header.fs_modal_sidebar.prefs_modal.show_sidebar.active div.contents_container.monkey_scroller div#prefs_output div#prefs_themes_customize label.clear_both.full_width' at this position. It may be overlapping the element you are trying to interact with. If you don't care about overlapping elements, try using node.trigger('click'). (Capybara::Poltergeist::MouseEventFailed)

See: https://github.com/wopian/material-slackthemes/commit/40e9414ff4d6559caa49662051dd48b8e82790d5#diff-9acb3b449bc3af1fc8cd1fda16cf21ceR13 and [Travis Log](https://travis-ci.org/wopian/material-slackthemes/builds/104378870#L260)

Temp. fix is to increase viewport height to ensure no theme `label` is below the output section.

**Comment by paracycle** [comment]
So it seems this is related to a Poltergeist bug where if the element is off the main view, it is not scrolled into view before a click. That's why setting the page height works for now (but won't work in the long run if you have more themes).

A better solution would be to upgrade the version of poltergeist gem to 1.8 or greater. I'll submit a PR for that.

**Comment by paracycle** [comment]
Oh and the link to the commit that fixes it is here: https://github.com/twalpole/poltergeist/commit/33ef995d3aed3b301909e0ed3a37523fd26e4932
